<?php require('includes/header.php');
?>
<div class="container">
    <div class="progress m-lg-5">
        <div class="progress-bar progress-bar" role="progressbar" style="width:33.33%">
            <a href="<?php echo $site_url;?>cart">Cart</a>
        </div>
        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" style="width:33.33%">
            <a href="<?php echo $site_url;?>checkout">Checkout</a>
        </div>
    </div>
        <!--REVIEW ORDER-->
    <div class="panel panel-info">
        <div class="panel-heading px-5">
            <strong>Review Order</strong> <div class="pull-right"><a class="afix-1" href="#"><button type="button" class="btn btn-sm btn-danger"><span class="fa fa-edit"></span>&nbsp;Update</button></a></div>
        </div>
        <div class="panel-body">
                <div class="row">
                    <div class=".col-xs-6 .col-sm-4 px-lg-5">
                        <img class="img-responsive m-3" src="//c1.staticflickr.com/1/466/19681864394_c332ae87df_t.jpg" width="" />
                    </div>

                    <div class=".col-xs-12 .col-sm-6 .col-md-8 col-lg-pull-10 m-3">
                        <div class=".col-xs-6 .col-sm-4">Product name</div>

                        <div class=".col-xs-6 .col-sm-4"><small>Quantity:<span>1</span></small></div>
                    </div>
                </div>
                <div class=".col-xs-6 .col-sm-4 pull-right px-5">
                    <h6><span>$</span>25.00</h6>
                </div>

            <div class="form-group"><hr /></div>
            <div class="form-group">
                <div class="col-xs-12 px-5">
                    <strong>Order Total</strong>
                    <div class="pull-right"><span>$</span><span>150.00</span></div>
                </div>
            </div>
            <div class="form-group"><hr /></div>
            <div class="text-right"><a href="<?php echo $site_url;?>pickup_details"><button type="button" class="btn btn-default btn-success">Proceed for pick up information&nbsp<span class="fa fa-arrow-right"></span></button></a></div>
    </div>
    <!--REVIEW ORDER END-->
</div>
<?php require('includes/footer.php');