<?php
require('includes/header.php');
?>
    <div class="container">
        <!-- Jumbotron Header -->
        <header class="jumbotron m-3">
            <img src="<?php echo $assets_dir;?>images/reachbottle_logo.png">
            <p class="lead">Welcome to Reach bottle, reach bottle is a market place where you can sell your empty/used bottles, cans and tetrapacks. Help our environment by recycling non degradable things.</p>
        </header>
    </div>
    <h3 style="text-align: center">
        <a href="<?php echo $site_url;?>vs/about" target="_blank">View Source</a>
    </h3>
<?php
require('includes/footer.php');