<?php require('includes/header.php');
?>
    <div class="container" style="background-color: #B1DDCF">
        <header class="jumbotron mx-5 pt-3 pb-3">
            <img class="img-responsive" width="270px" src="<?php echo $assets_dir;?>images/reachbottle_logo.png">
        </header>
        <table class="table table-bordered table-success" width="100%">
            <thead class="thead-default">
            <tr>
                <th >#</th>
                <th>User</th>
                <th>Order Date</th>
                <th>Pick up Schedule</th>
                <th>Order Status</th>
            </tr>
            </thead>

            <?php
            $i=1;
            if(is_array($order_information)) {
                foreach ($order_information as $order) {
                    ?>
                    <tbody>
                    <tr>
                        <th rowspan="7" scope="row"><?php echo $i; ?></th>
                        <td><?php echo $order['order']['name']; ?></td>
                        <td rowspan="3"><?php echo $order['order']['order_date_time']; ?></td>
                        <td rowspan="3"><?php echo $order['order']['delivery_schedule'] ?></td>
                        <td rowspan="3"><?php echo ($order['order']['order_served'] == '0') ? '<a href="#">Not Served</a>' : '<a href="#">Served</a>'; ?></td>
                    </tr>
                    <tr>
                        <td>Phone no.: <?php echo $order['order']['phone']; ?></td>
                    </tr>
                    <tr>
                        <td>Email: <?php echo $order['order']['email']; ?></td>
                    </tr>

                    <tr>
                        <td colspan="5" class="pl-5"><strong><em>Detail</em></strong></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <table width="100%" border="1" class="table-success">
                                <tr>
                                    <th>Item</th>
                                    <th>Quantity</th>
                                    <th>Amount</th>
                                </tr>
                                <?php
                                $total = 0;
                                foreach ($order['items'] as $item) {
                                    $total += $item['deposit_value'] * $item['qty'];
                                    ?>
                                    <tr>
                                        <td><?php echo $item['container_type']; ?></td>
                                        <td><?php echo $item['qty']; ?></td>
                                        <td class="text-right pr-3"><?php echo "$". number_format($item['deposit_value'] * $item['qty'],2); ?></td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                <tr>
                                    <td colspan="3" class="text-right pr-3"><strong>Order Total:</strong> $<?php echo number_format($total,2); ?></td>
                                </tr>

                            </table>
                            <hr/>
                        </td>
                    </tr>

                    </tbody>
                    <?php
                    $i++;
                }
            }else{
                ?>
                <tr>
                    <td colspan="5">No record found.</td>
                </tr>
                <?php
            }
                ?>
        </table>

    </div>
    <h3 style="text-align: center">
        <a href="<?php echo $site_url;?>vs/admin" target="_blank">View Source</a>
    </h3>
<?php require('includes/footer.php');