<?php
require('includes/header.php');
?>
    <div class="container">
        <div class="progress m-lg-5">
            <div class="progress-bar progress-bar-striped active" role="progressbar" style="width:33.33%;">
                <a class="nav-link" href="<?php echo $site_url;?>cart">Cart</a>
            </div>
        </div>

        <?php
        if($carts->rowCount() >0) {
            $order_total = 0;
            foreach ($carts as $cart) {
                ?>
                <div class="row product-row">
                    <!-- Products-->
                    <div class="col-xs-12 col-sm-7">
                        <div class="media">
                            <a class="pull-left" href="#"><img class="img-responsive"
                                                               src="<?php echo $assets_dir; ?>item_images/<?php echo $cart['item_id']; ?>.jpg "
                                                               width="120"></a>
                            <div class="media-body px-lg-4">
                                <h4 class="media-heading"><?php echo $cart['container_type']; ?></h4>
                                <p class="text-muted"><?php echo $cart['return_container_type']; ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-3">
                        Qty: <?php echo $cart['qty'];?><br />
                        Deposit amount: <?php echo $cart['deposit_value']*$cart['qty']; ?>
                    </div>
                    <div class="col-xs-12 col-sm-2">
                        <div class="btn-group" role="group" aria-label="..." style="margin-top:22px;">
                            <a href="<?php echo $site_url; ?>deletecartitem/<?php echo $cart['item_id']; ?>"
                               class="btn btn-default btn-danger" onclick="return confirm('Are you sure you want to delete this?');"><span class="fa fa-close"></span>Remove</a>
                        </div>
                    </div>
                </div>
                <hr />
                <?php
                $order_total+=$cart['deposit_value']*$cart['qty'];
            }
            ?>
            <div class="row product-row">
                <div class="col-xs-12 col-sm-12">
                    Order Total : <?php echo $order_total;?>
                </div>
            </div>
            <?php
        }else{
            ?>
            <div class="row product-row">
                <div class="col-xs-12 col-sm-12">
                    Your Cart is empty, please go to <a href="<?php echo $site_url;?>home">homepage</a> and add to cart.
                </div>
            </div>
            <?php
        }
        ?>
        <div class="row" style="margin-bottom:15px">
            <div class="col-xs-12">
                <div class="btn-group pull-left" role="group">
                    <a href="index.php"><button type="button" class="btn btn-default btn-info"><span class="fa fa-arrow-left"></span>&nbsp;Back to Products</button></a>
                    &nbsp;
                    <a href="<?php echo $site_url;?>pickup_details"><button type="button" class="btn btn-default btn-success"><span class="fa fa-shopping-cart"></span>&nbsp;Checkout&nbsp<span class="fa fa-arrow-right"></span></button></a>

                </div>
            </div>
        </div>

    </div>
<?php
require('includes/footer.php');