<?php
require('includes/header.php');
?>
    <div class="container">
        <!-- Jumbotron Header -->
        <header class="jumbotron m-3">
            <img src="<?php echo $assets_dir;?>images/reachbottle_logo.png">
            <p class="lead">Welcome to Reach bottle, reach bottle is a market place where you can sell your empty/used bottles, cans and tetrapacks. Help our environment by recycling non degradable things.</p>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <?php
            foreach($items as $item) {
                ?>
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card">
                        <img class="card-img-top" src="<?php echo $assets_dir;?>images/reachBottle_logo.jpg" alt="">
                        <div class="card-body">
                            <h4 class="card-title"><?php echo $item['container_type']?></h4>
                            <strong>Container type:</strong> <span><?php echo $item['return_container_type']?></span>
                            <br />
                            <strong>Value:</strong> <span><?php echo $item['deposit_value']?></span>
                        </div>
                        <form method="post" action="<?php echo $site_url;?>updatecart">
                            <div class="">
                                <input type="number" name="qty" class="form-control text-center" value="1" />
                            </div>
                            <div class="card-footer">
                                <input type="hidden" name="item_id" value="<?php echo $item['id']?>" />
                                <input type="submit" style="cursor: pointer;" name="add_to_cart" value="Add to Cart" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                </div>
                <?php
            }
            ?>

        </div>
        <!-- /.row -->
    </div>
<?php
require('includes/footer.php');