<?php
require('includes/header.php');
?>
    <div class="container">
        <div class="progress m-lg-5">
            <div class="progress-bar progress-bar" role="progressbar" style="width:33.33%">
                <a class="linkcolor" href="<?php echo $site_url;?>cart">Cart</a>
            </div>
            <div class="progress-bar progress-bar-success" role="progressbar" style="width:33.33%">
                <a href="<?php echo $site_url;?>checkout">Checkout</a>
            </div>
            <div class="progress-bar progress-bar progress-bar-striped active" role="progressbar" style="width:33.33%">
                <a href="<?php echo $site_url;?>pickup_details">Details</a>
            </div>
        </div>
        <div class="panel panel-info">
            <div class="panel-heading px-5">
               <strong>Customer Information</strong>
            </div>
            <div class="panel-body ">
                <form name="frmcontact" action="" method="post" class=" mx-5 mt-3">
                    <div class="form-group">
                        <label for="fname">First Name:</label>
                        <input type="text" class="form-control" name="fname" value="" required/>
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name:</label>
                        <input type="text" class="form-control" name="lname" value="" required/>
                    </div>
                    <div class="form-group">
                        <label for="address1">Address 1:</label>
                        <input type="text" class="form-control" name="lname" value="" required/>
                    </div>
                    <div class="form-group">
                        <label for="address2">Address 2:</label>
                        <input type="text" class="form-control" name="lname" value="" required/>
                    </div>
                    <div class="form-group">
                        <label for="postalcode">Postal Code:</label>
                        <input type="text" class="form-control" name="lname" value="" required/>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" name="email" value=""/>
                    </div>
                    <div class="form-group">
                        <label for="cell">Phone Number:</label>
                        <input type="tel" class="form-control" name="tel" value="">
                    </div>
                    <div class="well">
                        <div >
                            <input id="datetimepicker3" type="text" >
                            <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(function() {
                            $('#datetimepicker3').datetimepicker({
                                pickDate: false
                            });
                        });
                    </script>
                    <br>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>


<?php require('includes/footer.php');